### PR TITLE
Get resizeDown image from JED

### PR DESCRIPTION
**Pull request by nicksavov**
Potential fix for https://github.com/joomla-extensions/install-from-web-server/issues/27 . This one uses regex.

### CODE REVIEW

**Comment by andergmartins** [comment]
Code reviewed, looks good! :)

**Comment by losedk** [comment]
Tested. Works fine.

**Comment by losedk** [comment]
Should we get this merged, so it could be activated again? :)

**Comment by beat** [comment]
With the successful tests, I will now merge this PR.

But I would like to insist that this is a temporary workaround until JED API is able to return us downsampled cached images urls at the right size that we need as part of the JSON record.

E.g. Our JSON request could contain image_size_x and image_size_y parameters and the JSON reply return corresponding sized image-URL. That way, category-lists and individual entries would each have their own right-sized images.

**Comment by beat** [comment]
Also uploaded to staging now for final tests before going live!

**Comment by losedk** [comment]
@beat Great. Perhaps we should create an issue so it's not forgotten?

**Comment by losedk** [comment]
ahh there's one already :)

**Comment by nicksavov** [comment]
Thanks guys!

**Comment by beat** [comment]
@losedk do you have the URL to the JED API resized-image-sizes needed params / issue ?

**Pull request merged**
