### PR TITLE
Readd CSS file

### PR DESCRIPTION
**Pull request by nicksavov**
Fix for https://github.com/joomla-extensions/install-from-web-server/issues/17

Related:
https://github.com/joomla-extensions/install-from-web-server/pull/20

### CODE REVIEW

**Comment by zero-24** [comment]
@test successful

com_apps_fixed

Thanks @nicksavov

**Comment by nicksavov** [comment]
@beat, could we merge it and find out on staging? I can send in a fix if it doesn't work on there.

**Comment by nicksavov** [comment]
Closing in favor of https://github.com/joomla-extensions/install-from-web-client/pull/20

**Comment by beat** [comment]
@nicksavov I have reviewed this PR and here is my opinion:

CSS should stay grouped. Currently it is client-side, using semantic markup and classes. The CSS style which is in this unused server file (reduced by PR #20): https://github.com/joomla-extensions/install-from-web-server/blob/74716c10f7be24a1a357829927e52a5e7cbb1c6a/components/com_apps/css/apps.css should imho be added, with a different PR to this file imho: https://github.com/joomla-extensions/install-from-web-client/blob/master/plugins/installer/webinstaller/css/client.css (and its minified version) https://github.com/joomla-extensions/install-from-web-client/blob/master/plugins/installer/webinstaller/css/client.min.css

Alternatively, we could have a temporary inline-css server-side until we update and publish updated client too.

On  a separate not, the base url as proposed in this PR should imho not be used, as it doesn't use the CDN nor the rewrite-rule (and actually no file uses it anymore as not needed due to client-side-joomla-version-dependant styling.

If you or someone could do a PR for client-side CSS adding, it would be really great.

**Comment by beat** [comment]
Oh, ok, saw that it got closed and done why i was typing same :smile: , thanks @nicksavov

**Pull request closed without merging**
