### PR TITLE
Replaces legacy JED url with the CDN url for images

### PR DESCRIPTION
**Pull request by andergmartins**
Related to #7

### CODE REVIEW

**Comment by beat** [comment]
From code-reivew pov, i'm giving a :+1: 
Waiting for a successful tester before merge and upload to staging (and then hopefully to live quickly)

**Comment by andergmartins** [comment]
Instructions for testers:

# What to test

The domain used on the URL for images in the "Install From Web" tab.
Originally it was "http://extensions.joomla.org/" and now it is replaced by the content of the "CDN Prefix" param on com_app. The correct URL should be "https://extensionscdn.joomla.org/".

# How to test

## Preparing
1. Make sure you have this repo cloned, updated,installed and running locally;
1. Go to any other local Joomla site you have and manually update the file "/plugins/installer/webinstaller/webinstaller.php" changing the default value of the attribute `$appsBaseUrl` (line 21) pointing to your local installation of this repo;
1. Load the admin site found on this repo and load the System Global Configuration > com_app;
1. Set the param "CDN Prefix" to "https://extensionscdn.joomla.org/" ("URL & CDN Settings" tab) and save;


## Testing
1. Load the other local Joomla site;
1. Go to the Extensions Manager > Install from Web tab. You should see the grid/list of extensions instead of the warning about JED disabled.
1. Use the browser DOM inspector to select an image from any extension and check if the domain is pointing to the new CDN url you set on the step 4 while preparing.

**Comment by losedk** [comment]
Tested. All good!

skaermbillede 2015-04-22 kl 14 55 36

**Comment by andergmartins** [comment]
Nice!, thanks @losedk

**Comment by beat** [comment]
Thanks @andergmartins for the MR and @losedk for the tests! Merging!

**Comment by andergmartins** [comment]
Nice, thanks. You're welcome!

**Pull request merged**
