### PR TITLE
Updates to list view

### PR DESCRIPTION
**Pull request by C-Lodder**
Wrap the entire list item in an `<a>`

### CODE REVIEW

**Comment by brianteeman** [comment]
this is not correct as it kills the link to the reviews

**Comment by mbabker** [comment]
Right.

The current setup is pretty similar, only the title/description text links to the item page (it just has some CSS rules to make it look like a link).  So we do need to either keep it JavaScript-ish or come up with a solution that doesn't kill the reviews link.

**Comment by brianteeman** [comment]
actually i had to add the css here https://github.com/joomla/joomla-cms/pull/19421

**Comment by C-Lodder** [comment]
@brianteeman There is a link to the reviews page on the 2nd page

**Comment by brianteeman** [comment]
This is not the time to change the functionality

**Comment by mbabker** [comment]
For now the aim is to have feature/UI parity with the existing 3.x stuff.  We can get into other changes later (that should be made to both versions of the markup), let's try to keep the behavior consistent regardless of major Joomla version in use.

**Comment by brianteeman** [comment]
and consistent across the views ;)

**Comment by C-Lodder** [comment]
Sire no problem then. If that's the agreed scope for now, I'm cool with that.

**Pull request closed without merging**
